<?php
namespace common\widgets\fgrid;

use common\components\FHtml;

class FCarousel extends FGrid
{
    public function run()
    {
        $this::prepareData();

        $result = '';

        $result .= $this->RenderWidget('fcarousel', array(
                'data' => $this->data,
                'items' => $this->items,
                'title' => $this->title,
                'overview' => $this->overview,
                'display_type' => $this->display_type,
                'title_display_type' => $this->title_display_type,
                'width_css' => $this->width_css,
                'background_css' => $this->background_css,
                'alignment' => $this->alignment,
                'columns_count' => $this->columns_count,
                'items_count' => $this->items_count,
                'color' => $this->color,
                'image_width' => $this->image_width,
                'image_height' => $this->image_height,
                'field_title' => $this->field_title,
                'field_overview' => $this->field_overview,
                'item_layout' => $this->item_layout,
                'label_viewmore' => $this->label_viewmore,
                'image_folder' => $this->image_folder,
                'style' => $this->style,
                'item_style' => $this->item_style,
                'link_url' => $this->link_url,
                'show_viewmore' => $this->show_viewmore,
                'is_preview' => $this->is_preview,
                'margin' => $this->margin,
                'viewmore_url' => $this->viewmore_url,
                'show_border' => $this->show_border,
                'items_filter' => $this->items_filter,
                'object_type' => $this->object_type
            )
        );

        return $result;
    }

    protected function prepareData()
    {
        $this->display_type = !empty($this->display_type) ? $this->display_type : '1';

        $this->title = !empty($this->title) ? $this->title : '';
        $this->overview = !empty($this->overview) ? $this->overview : '';

        $this->title_display_type = !empty($this->title_display_type) ? $this->title_display_type : FHtml::HEADLINE_TYPE_CENTER_V2;

        $this->item_layout = !empty($this->item_layout) ? $this->item_layout : FHtml::LAYOUT_NO_LABEL;

        $this->image_height = !empty($this->image_height) ? $this->image_height : 150;

        $this->pagination = null;

        parent::prepareData(); // TODO: Change the autogenerated stub
    }
}

?>