<?php
namespace common\widgets\fgrid;

use common\components\FHtml;
use common\widgets\BaseWidget;
use yii\helpers\BaseInflector;

class FGrid extends BaseWidget
{
    public function run()
    {

        $this::prepareData();

        $result = '';

        $result .= $this->RenderWidget($this->display_type, array(
                'data' => $this->data,
                'items' => $this->items,
                'title' => $this->title,
                'overview' => $this->overview,
                'title_display_type' => $this->title_display_type,
                'width_css' => $this->width_css,
                'background_css' => $this->background_css,
                'alignment' => $this->alignment,
                'columns_count' => $this->columns_count,
                'items_count' => $this->items_count,
                'color' => $this->color,
                'image_width' => $this->image_width,
                'image_height' => $this->image_height,
                'field_title' => $this->field_title,
                'field_overview' => $this->field_overview,
                'field_type' => $this->field_type,
                'field_type_colors' => $this->field_type_colors,
                'item_layout' => $this->item_layout,
                'label_viewmore' => $this->label_viewmore,
                'image_folder' => $this->image_folder,
                'link_url' => $this->link_url,
                'show_viewmore' => $this->show_viewmore,
                'is_preview' => $this->is_preview,
                'margin' => $this->margin,
                'viewmore_url' => $this->viewmore_url,
                'display_type' => $this->display_type,
                'show_border' => $this->show_border,
                'show_panel' => $this->show_panel,
                'show_price' => $this->show_price,
                'style' => $this->style,
                'item_style' => $this->item_style,
                'show_rate' => $this->show_rate,
                'show_headline' => $this->show_headline,
                'items_filter' => $this->items_filter,
                'object_type' => $this->object_type
            )
        );

        if (isset($this->pagination)) {
            $result .= \common\widgets\fpager\FPager::widget([
                'pagination' => $this->pagination,
                'total_this_page' => count($this->items),
                'total' => $this->data->totalCount,
                'keyword' => $this->keyword]);
        }

        return $result;
    }

    protected function prepareData()
    {
        if (empty($this->object_type))
            $this->object_type = 'product';

        if ($this->alignment = 'pull-left') {
            $this->alignment = '';
        }

        $module = FHtml::getModelModule($this->object_type);
        if (!isset($this->link_url))
            $this->link_url = !empty($module)? $module . '/' . $this->object_type : $this->object_type; //$this->object_type . '/view';

        if (empty($this->image_folder))
            $this->image_folder = FHtml::getImageFolder($this->object_type);

        if (empty($this->display_type))
            $this->display_type =  'fgrid2';//FHtml::generateRandomInArray(['flist', 'fgrid1', 'fgrid2', 'fgrid3', 'fmasonry', 'ftabs', 'fcollapsible']);

        if (!isset($this->margin))
            $this->margin = 20;

        parent::prepareData(); // TODO: Change the autogenerated stub
    }
}

?>