<?php
namespace common\widgets\fboxlist;

use common\components\FHtml;
use common\widgets\BaseWidget;

class FBoxList extends BaseWidget
{
    public $icon_border_type;
    public $icon_bg_type;
    public $icon_size;

    public function run()
    {
        self::prepareData();

        return $this->RenderWidget($this->display_type,
            ['items' => $this->items,
                'field_title' => $this->field_title,
                'field_overview' => $this->field_overview,
                'color' => $this->color, 'icon_border_type' => $this->icon_border_type, 'icon_bg_type' => $this->icon_bg_type, 'icon_size' => $this->icon_size,
                'items_count' => $this->items_count]);
    }

    protected function prepareData()
    {
        if (empty($this->object_type))
            $this->object_type = 'cms_about';

        if (empty($this->items_count))
            $this->items_count = 4;

        if (empty($this->display_type))
            $this->display_type = 'serviceslist' . FHtml::generateRandomInArray(['1', '2', '3', '4', '5', '6']);

        if (empty($this->width_css)) {
            $this->width_css = FHtml::WIDGET_WIDTH_FULL;
        }

        if (empty($this->icon_border_type))
            $this->icon_border_type = FHtml::generateRandomInArray(['rounded-x', '', 'round-2x', 'round-4x']);

        if (empty($this->icon_bg_type))
            $this->icon_bg_type = FHtml::generateRandomInArray(['bg', 'color']);

        if (empty($this->icon_size))
            $this->icon_size = FHtml::generateRandomInArray(['icon-sm', 'icon-md', '']);

        parent::prepareData(); // TODO: Change the autogenerated stub
    }
}

?>