<?php
namespace common\widgets\fboxlist;

use backend\modules\cms\models\CmsService;
use common\components\FHtml;

class FService extends FBoxList
{
    public function run()
    {
        self::prepareData();

        return $this->RenderWidget($this->display_type,
            ['items' => $this->items,
                'field_title' => $this->field_title,
                'field_overview' => $this->field_overview,
                'color' => $this->color, 'icon_border_type' => $this->icon_border_type, 'icon_bg_type' => $this->icon_bg_type, 'icon_size' => $this->icon_size,
                'items_count' => $this->items_count]);
    }

    protected function prepareData()
    {
        if (empty($this->object_type))
            $this->object_type = 'cms_service';

        if (empty($this->items_count))
            $this->items_count = 3;

        if (empty($this->display_type))
            $this->display_type = 'serviceslist1'; //rand(1, 6);

        if (!isset($this->items)) {
            $this->items = CmsService::findAll(['is_active' => 1]);
        }

        parent::prepareData(); // TODO: Change the autogenerated stub
    }
}

?>