<?php

/**
 * @package   yii2-grid
 * @author    Kartik Visweswaran <kartikv2@gmail.com>
 * @copyright Copyright &copy; Kartik Visweswaran, Krajee.com, 2014 - 2016
 * @version   3.1.2
 */

namespace common\widgets;

use common\components\FConfig;
use common\components\FHtml;
use common\widgets\FListView;
use kartik\editable\Editable;
use kartik\grid\DataColumn;
use kartik\grid\GridExportAsset;
use kartik\grid\GridFloatHeadAsset;
use kartik\grid\GridPerfectScrollbarAsset;
use kartik\grid\GridResizeColumnsAsset;
use kartik\grid\GridView;
use kartik\grid\GridViewAsset;
use kartik\grid\Module;
use kartik\grid\RadioColumn;
use kartik\grid\SerialColumn;
use Yii;
use yii\base\InvalidConfigException;
use yii\bootstrap\ButtonDropdown;
use yii\data\ActiveDataProvider;
use yii\grid\ActionColumn;
use yii\helpers\ArrayHelper;
use yii\helpers\BaseInflector;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\helpers\StringHelper;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\web\View;
use yii\widgets\Pjax;
use kartik\base\Config;
use kartik\sortable\SortableAsset;
use yii\jui\JuiAsset;

/**
 * Enhances the Yii GridView widget with various options to include Bootstrap specific styling enhancements. Also
 * allows to simply disable Bootstrap styling by setting `bootstrap` to false. Includes an extended data column for
 * column specific enhancements.
 *
 *
 * @author Kartik Visweswaran <kartikv2@gmail.com>
 * @since  1.0
 */
class FGridWidget extends FGridView
{
    public function init()
    {
        $this->display_type = FHtml::DISPLAY_TYPE_WIDGET;
        $this->layout = '{items}';
        $this->toolbar = '';
        $this->pjax = true;
        return parent::init(); // TODO: Change the autogenerated stub
    }
}
