<?php
namespace common\widgets\fslider;

use common\components\FHtml;

class FCMSSlide extends FSlider
{
    protected function prepareData()
    {
        $this->object_type = 'cms_slide';

        if (empty($this->image_folder))
            $this->image_folder = SLIDER_DIR;

        if (!isset($this->items))
            $this->items = FHtml::getModels('cms_slide');

        parent::prepareData(); // TODO: Change the autogenerated stub
    }
}

?>