<?php
namespace common\widgets\fsocialshare;

use common\widgets\BaseWidget;

class FChat extends BaseWidget
{
    public $chat_url;

    protected function prepareData()
    {
        $this->display_type = !empty($this->display_type) ? $this->display_type : 'chat_fb1.php';
        parent::prepareData(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        self::prepareData();

        return $this->RenderWidget($this->display_type,
            [
                'chat_url' => $this->chat_url
               ]);
    }
}

?>