<?php
namespace common\widgets\fsocialshare;

use common\widgets\BaseWidget;

class FGoogleAnalytic extends BaseWidget
{
    public $google_analytic_key;

    protected function prepareData()
    {
        $this->display_type = !empty($this->display_type) ? $this->display_type : 'google_analytic.php';

        parent::prepareData(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        self::prepareData();

        return $this->render($this->display_type ,
            [
                'google_analytic_key' => $this->google_analytic_key,
            ]);
    }
}

?>