<?php
namespace common\widgets\fsocialshare;

use common\widgets\BaseWidget;

class FSocialShare extends BaseWidget
{
    public $show_icon;
    public $show_count;
    public $size;
    public $float;
    public $items;
    public $shape;

    protected function prepareData()
    {
        parent::prepareData(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        self::prepareData();

        return $this->render('socialshare' . $this->display_type,
            [
                'title' => $this->title,
                'overview' => $this->overview,
                'show_icon' => $this->show_icon,
                'show_count' => $this->show_count,
                'size' => $this->size,
                'float' => $this->float,
                'items' => $this->items,
                'shape' => $this->shape,
                'link_url' => $this->link_url,
                'container' => $this->container,
                'width_css' => $this->width_css]);
    }
}

?>