<?php
namespace common\widgets\fcategory;

use common\components\FHtml;
use common\widgets\BaseWidget;

class FCategory extends BaseWidget
{
    public function run()
    {
        $this::prepareData();

        return $this->RenderWidget($this->display_type, array(
                'items' => $this->items,
                'title' => $this->title,
                'overview' => $this->overview,
                'title_display_type' => $this->title_display_type,
                'width_css' => $this->width_css,
                'background_css' => $this->background_css,
                'alignment' => $this->alignment,
                'columns_count' => $this->columns_count,
                'items_count' => $this->items_count,
                'color' => $this->color,
                'image_width' => $this->image_width,
                'image_height' => $this->image_height,
                'field_title' => $this->field_title,
                'field_overview' => $this->field_overview,
                'item_layout' => $this->item_layout,
                'label_viewmore' => $this->label_viewmore,
                'image_folder' => $this->image_folder,
                'link_url' => $this->link_url,
                'show_viewmore' => $this->show_viewmore,
                'is_preview' => $this->is_preview,
                'style' => $this->style,
                'item_style' => $this->item_style,
                'viewmore_url' => $this->viewmore_url,
                'show_border' => $this->show_border,
                'items_filter' => $this->items_filter,
                'object_type' => $this->object_type
            )
        );
    }

    protected function prepareData()
    {
        if (empty($this->admin_url))
            $this->admin_url = FHtml::createUrl('object-category/index', ['object_type' => $this->object_type], ['frontend' => 'backend']);

        if ($this->alignment = 'pull-left') {
            $this->alignment = '';
        }

        if (empty($this->image_folder))
            $this->image_folder = CATEGORY_DIR;

        if (empty($this->display_type))
            $this->display_type = 'ful';

        if (empty($this->title))
            $this->title = FHtml::t('common', 'Categories');

        if (empty($this->title_display_type))
            $this->title_display_type = 'headline-v2 bg-color-light';

        if (empty($this->link_url) && !empty($this->object_type))
            $this->link_url = '/' . $this->object_type . '/list';

        if (empty($this->color))
            $this->color = FHtml::currentApplicationMainColor();

        if (!isset($this->items)) {
            $this->items = FHtml::getCategories($this->object_type, [], false);
        }

        parent::prepareData(); // TODO: Change the autogenerated stub
    }
}

?>